/* Seve Zavala · portfolio
   Plain JS, no build step. Four jobs:
   1. mobile nav toggle
   2. highlight the nav link for the section in view
   3. reveal sections on scroll
   4. render the QA Lab from lab/results.js (generated by scripts/lab-results.mjs) */

(function () {
  'use strict';

  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* ---------- 1. Mobile nav ---------- */

  const toggle = $('.nav-toggle');
  const links = $('#nav-links');

  function setMenu(open) {
    toggle.setAttribute('aria-expanded', String(open));
    toggle.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
    links.classList.toggle('open', open);
  }

  if (toggle && links) {
    toggle.addEventListener('click', () => setMenu(toggle.getAttribute('aria-expanded') !== 'true'));
    links.addEventListener('click', (e) => { if (e.target.closest('a')) setMenu(false); });
    document.addEventListener('keydown', (e) => { if (e.key === 'Escape') setMenu(false); });
  }

  /* ---------- 2. Active section in nav ---------- */

  const navAnchors = $$('.nav-links > a[href^="#"]');
  const sections = navAnchors
    .map((a) => document.getElementById(a.getAttribute('href').slice(1)))
    .filter(Boolean);

  if ('IntersectionObserver' in window && sections.length) {
    const byId = new Map(navAnchors.map((a) => [a.getAttribute('href').slice(1), a]));
    const spy = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        navAnchors.forEach((a) => a.removeAttribute('aria-current'));
        const a = byId.get(entry.target.id);
        if (a) a.setAttribute('aria-current', 'true');
      });
    }, { rootMargin: '-40% 0px -55% 0px' });
    sections.forEach((s) => spy.observe(s));
  }

  /* ---------- 3. Reveal on scroll ---------- */

  const revealTargets = $$('.section-head, .split, .card, .work-card, .timeline-item, .steps li, .lab, .focus-item');
  if (!reducedMotion && 'IntersectionObserver' in window) {
    revealTargets.forEach((el) => el.classList.add('reveal'));
    const io = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) { entry.target.classList.add('in'); io.unobserve(entry.target); }
      });
    }, { threshold: 0.12 });
    revealTargets.forEach((el) => io.observe(el));
  }

  /* ---------- 4. QA Lab ---------- */

  const results = window.LAB_RESULTS;
  const labRoot = $('#qa-lab');

  function el(tag, attrs = {}, children = []) {
    const node = document.createElement(tag);
    Object.entries(attrs).forEach(([k, v]) => {
      if (k === 'class') node.className = v;
      else if (k === 'text') node.textContent = v;
      else node.setAttribute(k, v);
    });
    children.forEach((c) => node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c));
    return node;
  }

  function pad2(n) { return String(n).padStart(2, '0'); }
  function ms(n) { return n >= 1000 ? (n / 1000).toFixed(1) + 's' : Math.round(n) + 'ms'; }

  function renderLab() {
    if (!results || !labRoot) return;

    const { totals, projects, groups, generatedAt } = results;
    // Skipped tests neither passed nor failed, so they leave the denominator.
    const ran = totals.tests - totals.skipped;
    const passingPct = ran ? Math.round((totals.passed / ran) * 100) : 0;

    $('[data-lab="tests"]', labRoot).textContent = totals.tests;
    $('[data-lab="browsers"]', labRoot).textContent = projects.length;
    $('[data-lab="passing"]', labRoot).textContent = passingPct + '%';
    $('[data-lab="projects"]', labRoot).textContent = projects.join(' · ');
    $('[data-lab="foot"]', labRoot).textContent = `Full regression suite · ${totals.tests} tests · ${projects.length} browsers`;

    if (generatedAt) {
      const when = new Date(generatedAt);
      $('[data-lab="generated"]', labRoot).textContent =
        `Recorded ${when.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })} · ${ms(totals.durationMs)} wall clock`;
    }

    // Test groups (one per spec file / describe block)
    const list = $('[data-lab="groups"]', labRoot);
    list.textContent = '';
    groups.forEach((group, i) => {
      const allPass = group.tests.every((t) => t.status === 'passed' || t.status === 'skipped');
      const panelId = `lab-group-${i}`;
      const items = group.tests.map((t) =>
        el('li', {}, [
          el('span', { class: t.status === 'passed' ? 'ok' : t.status === 'skipped' ? 'log-skip' : 'fail', text: t.status === 'passed' ? '✓' : t.status === 'skipped' ? '–' : '✕' }),
          el('span', { text: `${t.title} · ${t.project}` }),
          el('time', { text: ms(t.duration) }),
        ])
      );
      const panel = el('ul', { class: 'lab-group-list', id: panelId, hidden: '' }, items);
      const btn = el('button', { class: 'lab-group-btn', type: 'button', 'aria-expanded': 'false', 'aria-controls': panelId }, [
        el('span', { class: 'lab-group-status' + (allPass ? '' : ' fail'), text: allPass ? '✓' : '✕', 'aria-hidden': 'true' }),
        el('span', { class: 'lab-group-name', text: group.name }),
        el('span', { class: 'lab-group-count', text: `${pad2(group.tests.length)} tests` }),
        el('span', { class: 'lab-group-chev', 'aria-hidden': 'true', text: '⌄' }),
      ]);
      btn.addEventListener('click', () => {
        const open = btn.getAttribute('aria-expanded') === 'true';
        btn.setAttribute('aria-expanded', String(!open));
        panel.hidden = open;
      });
      list.appendChild(el('div', { class: 'lab-group', role: 'listitem' }, [btn, panel]));
    });

    // Replay the recorded run into the terminal panel
    const log = $('[data-lab="log"]', labRoot);
    const replay = $('[data-lab="replay"]', labRoot);

    function line(cls, text) {
      const span = el('span', { class: cls, text });
      log.appendChild(span);
      log.appendChild(document.createTextNode('\n'));
      log.scrollTop = log.scrollHeight;
    }

    const sleep = (t) => new Promise((r) => setTimeout(r, reducedMotion ? 0 : t));

    // Keep the whole replay to roughly five seconds no matter how large the
    // suite grows, so the animation stays watchable and the lab's own test
    // isn't racing a clock that moves with every spec we add.
    const totalLines = groups.reduce((n, g) => n + g.tests.length, 0);
    const perLine = Math.max(15, Math.min(120, Math.round(5000 / Math.max(totalLines, 1))));

    async function runReplay() {
      replay.disabled = true;
      log.textContent = '';
      line('log-prompt', `› npx playwright test  (${projects.join(', ')})`);
      line('log-dim', `Running ${totals.tests} tests using ${projects.length} projects`);
      await sleep(400);

      for (const group of groups) {
        line('log-accent', `\n${group.file} › ${group.name}`);
        for (const t of group.tests) {
          const mark = t.status === 'passed' ? '  ✓ ' : t.status === 'skipped' ? '  – ' : '  ✘ ';
          const cls = t.status === 'passed' ? 'log-pass' : t.status === 'skipped' ? 'log-skip' : 'log-fail';
          line(cls, `${mark}[${t.project}] ${t.title} (${ms(t.duration)})`);
          await sleep(perLine);
        }
      }

      await sleep(300);
      const parts = [`${totals.passed} passed`];
      if (totals.failed) parts.push(`${totals.failed} failed`);
      if (totals.skipped) parts.push(`${totals.skipped} skipped`);
      if (totals.flaky) parts.push(`${totals.flaky} flaky`);
      line('log-prompt', `\n  ${parts.join(', ')} (${ms(totals.durationMs)})`);
      line('log-dim', totals.failed ? 'Run finished with failures.' : 'Run finished. Every test above ran against this page in CI.');
      log.setAttribute('data-state', 'done');
      replay.disabled = false;
    }

    replay.addEventListener('click', runReplay);
  }

  renderLab();

  /* ---------- Footer year ---------- */
  const year = $('[data-year]');
  if (year) year.textContent = String(new Date().getFullYear());
})();
